version: "3.8"
services:
  app:
    image: textdetection:01
    container_name: textdetection
    runtime: nvidia
    build: 
      context: .
      network: host
      dockerfile: ./Dockerfile
      args:
        - DEV_textdetection=1
    env_file:
      - ./.env_vm
    ports:
      - "7485:7485"
    volumes:
      - .:/app
      - /home/andreas/data:/app/data