version: "3.8"
services:
  app:
    image: textdetection:01
    container_name: textdetection
    runtime: nvidia
    build: 
      context: .
      network: host
      dockerfile: ./Dockerfile
      args:
        - DEV_textdetection=1
    environment:
    #- AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    #- AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - NVIDIA_VISIBLE_DEVICES=all
    - HOME=/app
    - DATA_ROOT=/app/data
    ports:
      - "8888:8888"
    volumes:
      - .:/app
      - ./data:/app/data